version: '3.3'
services:

    arches:
      container_name: arches
      image: asisgtm/arches:721
      build:
        context: .
        dockerfile: ./Dockerfile
      command: run_arches
      volumes:
        - arches-log:/arches/arches/logs
        - arches-static:/static_root
        - ./danam:/web_root/danam
        #- ./docker/settings_local.py:/web_root/danam/settings_local.py
        #- ./archesssss:/web_root/arches/
        - ./docker:/web_root/docker
        - arches-uploadedfiles:/web_root/danam/danam/uploadedfiles
        - ./docker/entrypoint.sh:/web_root/entrypoint.sh
      env_file:
        - ./docker/env_file.env
      ports:
        - '127.0.0.1:8000:8000'
      depends_on:
        - db
        - elasticsearch
        - rabbitmq

    db:
      container_name: db
      image: kartoza/postgis:14-3.3
      volumes:
        - postgres-data:/var/lib/postgresql
        - postgres-log:/var/log/postgresql
        - ./docker/init-unix.sql:/docker-entrypoint-initdb.d/init.sql # to set up the DB template
      ports:
        - '127.0.0.1:5432:5432'
      env_file:
        - ./docker/env_file.env

    elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "127.0.0.1:9200:9200"
        - "127.0.0.1:9300:9300"
      env_file:
        - ./docker/env_file.env

    rabbitmq:
      image: rabbitmq:3.11.5-management
      container_name: rabbitmq
      privileged: true
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-log:/var/log/rabbitmq/
        #  - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
        #  - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
        #  - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
      env_file:
        - ./docker/env_file.env
      ports:
        - "127.0.0.1:5672:5672"
        - "127.0.0.1:15672:15672"

    
volumes:
  arches-log:
  arches-static:
  arches-uploadedfiles: 
  postgres-data:
  postgres-log:
  elasticsearch-data:
  rabbitmq-data:
  rabbitmq-log:
  letsencrypt:
  letsencrypt-log:
  letsencrypt-acme-challenge:
